default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cdp_web_manyo_task_development

test:
  <<: *default
  database: cdp_web_manyo_task_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
